import { ThemeFx, withAlpha } from '@/src/theme';
import { StyleSheet } from 'react-native';

export const createThemeStudioStyles = (colors: any) =>
    StyleSheet.create({
        container: {
            borderRadius: 14,
            borderWidth: 1.5,
            borderColor: colors.border,
            backgroundColor: colors.surfaceLighter,
            padding: 10,
            gap: 10,
        },
        sectionLabel: {
            color: colors.textMuted,
            fontSize: 10,
            fontWeight: '800',
            textTransform: 'uppercase',
            letterSpacing: 0.8,
        },
        row: { flexDirection: 'row', gap: 6 },
        grow: { flex: 1 },
        tabBtn: {
            flex: 1,
            borderRadius: 10,
            borderWidth: 1.5,
            borderColor: colors.border,
            backgroundColor: colors.surface,
            paddingVertical: 9,
            alignItems: 'center',
            justifyContent: 'center',
        },
        tabBtnActive: {
            borderColor: colors.primary.DEFAULT,
            backgroundColor: withAlpha(colors.primary.DEFAULT, '18'),
        },
        tabBtnText: { color: colors.textMuted, fontSize: 12, fontWeight: '800' },
        tabBtnTextActive: { color: colors.primary.DEFAULT },
        chip: {
            borderRadius: 999,
            borderWidth: 1.5,
            borderColor: colors.border,
            paddingHorizontal: 7,
            paddingVertical: 5,
            backgroundColor: colors.surface,
        },
        chipActive: {
            borderColor: colors.primary.DEFAULT,
            backgroundColor: withAlpha(colors.primary.DEFAULT, '18'),
        },
        chipText: { color: colors.textMuted, fontSize: 10, fontWeight: '800' },
        chipTextActive: { color: colors.primary.DEFAULT },
        compactInput: {
            borderWidth: 1.5,
            borderColor: colors.border,
            borderRadius: 10,
            backgroundColor: colors.surface,
            color: colors.text,
            fontSize: 12,
            fontWeight: '700',
            paddingHorizontal: 10,
            paddingVertical: 8,
        },
        card: {
            borderWidth: 1.5,
            borderColor: colors.border,
            borderRadius: 12,
            backgroundColor: colors.surface,
            padding: 9,
            gap: 6,
        },
        cardTitle: { color: colors.text, fontWeight: '900', fontSize: 13 },
        cardSub: { color: colors.textMuted, fontSize: 11 },
        compactMetaLine: {
            color: colors.textMuted,
            fontSize: 10,
            fontWeight: '700',
        },
        badge: {
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: 999,
            paddingHorizontal: 7,
            paddingVertical: 3,
            backgroundColor: colors.surfaceLighter,
        },
        badgeText: {
            fontSize: 9,
            fontWeight: '900',
            color: colors.textMuted,
            textTransform: 'uppercase',
            letterSpacing: 0.6,
        },
        actionBtn: {
            borderRadius: 9,
            borderWidth: 1.5,
            borderColor: colors.border,
            backgroundColor: colors.surfaceLighter,
            paddingVertical: 7,
            paddingHorizontal: 8,
            alignItems: 'center',
            justifyContent: 'center',
        },
        actionBtnPrimary: {
            borderColor: colors.primary.DEFAULT,
            backgroundColor: withAlpha(colors.primary.DEFAULT, '18'),
        },
        actionBtnText: { color: colors.text, fontSize: 10, fontWeight: '800' },
        actionBtnTextPrimary: { color: colors.primary.DEFAULT },
        helperError: { color: colors.red, fontSize: 11, fontWeight: '700' },
        helperOk: { color: colors.green, fontSize: 11, fontWeight: '700' },
        input: {
            borderWidth: 1.5,
            borderColor: colors.border,
            borderRadius: 12,
            backgroundColor: colors.surface,
            color: colors.text,
            fontSize: 14,
            fontWeight: '700',
            paddingHorizontal: 12,
            paddingVertical: 9,
        },
        modeBtn: {
            borderRadius: 10,
            borderWidth: 1.5,
            borderColor: colors.border,
            paddingVertical: 9,
            paddingHorizontal: 10,
            backgroundColor: colors.surface,
            alignItems: 'center',
        },
        modeBtnActive: {
            borderColor: colors.primary.DEFAULT,
            backgroundColor: withAlpha(colors.primary.DEFAULT, '18'),
        },
        modeBtnText: { color: colors.textMuted, fontSize: 12, fontWeight: '800' },
        modeBtnTextActive: { color: colors.primary.DEFAULT },
        colorRow: {
            borderRadius: 12,
            borderWidth: 1.5,
            borderColor: colors.border,
            backgroundColor: colors.surface,
            padding: 9,
            gap: 7,
        },
        colorRowTitle: { color: colors.text, fontSize: 12, fontWeight: '800' },
        colorRowSub: { color: colors.textMuted, fontSize: 11 },
        swatch: {
            width: 24,
            height: 24,
            borderRadius: 8,
            borderWidth: 1.5,
            borderColor: colors.border,
            backgroundColor: colors.surfaceLighter,
        },
        previewTitle: { color: colors.text, fontSize: 12, fontWeight: '900', marginBottom: 6 },
        previewCard: {
            borderRadius: 12,
            borderWidth: 1.5,
            padding: 9,
            minHeight: 124,
            justifyContent: 'space-between',
            ...ThemeFx.shadowSm,
        },
        previewBtn: {
            alignSelf: 'flex-start',
            paddingHorizontal: 10,
            paddingVertical: 5,
            borderRadius: 999,
            borderWidth: 1,
        },
        previewBtnText: { fontSize: 10, fontWeight: '900' },
        statusCard: {
            borderRadius: 11,
            borderWidth: 1.5,
            borderColor: colors.border,
            backgroundColor: colors.surface,
            padding: 9,
            gap: 3,
        },
        liveFeedbackBanner: {
            borderRadius: 10,
            borderWidth: 1.5,
            paddingHorizontal: 10,
            paddingVertical: 7,
            backgroundColor: colors.surface,
        },
        liveFeedbackOk: {
            borderColor: withAlpha(colors.green, '66'),
            backgroundColor: withAlpha(colors.green, '14'),
        },
        liveFeedbackWarn: {
            borderColor: withAlpha(colors.yellow, '66'),
            backgroundColor: withAlpha(colors.yellow, '14'),
        },
        liveFeedbackText: {
            fontSize: 11,
            fontWeight: '800',
        },
        subtlePanel: {
            borderRadius: 11,
            borderWidth: 1.5,
            borderColor: colors.border,
            backgroundColor: colors.surface,
            padding: 8,
            gap: 7,
        },
        disabledBtn: {
            opacity: 0.45,
        },
    });
