import { useTheme } from '@/src/hooks/useTheme';
import { ThemeFx, withAlpha } from '@/src/theme';
import { useMemo } from 'react';
import { Platform, StyleSheet } from 'react-native';

export const createSocialStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    loggedOutContainer: {
        alignItems: 'center',
        paddingHorizontal: 32,
        paddingTop: 80,
    },
    loggedOutIcon: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: colors.surfaceLighter,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 28,
        borderWidth: 1.5,
        borderColor: colors.border,
        ...ThemeFx.shadowSm,
    },
    loggedOutTitle: {
        fontSize: 28,
        fontWeight: '900',
        color: colors.text,
        textAlign: 'center',
        marginBottom: 14,
        letterSpacing: -1,
    },
    loggedOutSub: {
        fontSize: 16,
        color: colors.textMuted,
        textAlign: 'center',
        lineHeight: 24,
        marginBottom: 44,
    },
    loginBtn: {
        backgroundColor: colors.primary.DEFAULT,
        paddingVertical: 18,
        paddingHorizontal: 32,
        borderRadius: 16,
        width: '100%',
        alignItems: 'center',
        marginBottom: 14,
        ...ThemeFx.shadowSm,
    },
    loginBtnText: {
        color: colors.onPrimary,
        fontSize: 17,
        fontWeight: '900',
        letterSpacing: 0.5,
    },
    signupBtn: {
        backgroundColor: colors.surface,
        paddingVertical: 18,
        paddingHorizontal: 32,
        borderRadius: 16,
        width: '100%',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    signupBtnText: {
        color: colors.text,
        fontSize: 17,
        fontWeight: '800',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        height: 76,
        backgroundColor: colors.background,
        zIndex: 10,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
    },
    title: {
        color: colors.text,
        fontWeight: '900',
        fontSize: 26,
        letterSpacing: -1.2,
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: '900',
        color: colors.text,
        letterSpacing: -0.5,
    },
    headerSubtitle: {
        fontSize: 13,
        color: colors.textMuted,
        fontWeight: '700',
    },
    iconBtn: {
        width: 44,
        height: 44,
        borderRadius: 14,
        backgroundColor: colors.surfaceLighter,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    inboxBadge: {
        position: 'absolute',
        top: 6,
        right: 12,
        backgroundColor: colors.primary.DEFAULT,
        minWidth: 18,
        height: 18,
        borderRadius: 9,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 4,
        borderWidth: 1.5,
        borderColor: colors.surface,
    },
    inboxBadgeText: {
        color: colors.onPrimary,
        fontSize: 10,
        fontWeight: '900',
    },
    headerActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        zIndex: 10,
    },
    publicBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: colors.primary.DEFAULT,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 14,
        ...ThemeFx.shadowSm,
    },
    publicBtnText: {
        color: colors.onPrimary,
        fontSize: 13,
        fontWeight: '900',
        letterSpacing: 0.5,
    },
    headerIconBtn: {
        width: 48,
        height: 48,
        borderRadius: 16,
        backgroundColor: colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
        ...ThemeFx.shadowSm,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        zIndex: 10,
        flex: 1,
    },
    headerLoadingWrapper: {
        marginLeft: 12,
    },
    headerCenterIconWrapper: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
        alignItems: 'center',
        justifyContent: 'center',
        pointerEvents: 'none',
    },
    headerCenterIcon: {
        width: 100,
        height: 100,
        resizeMode: 'contain',
    },
    headerActionsBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        zIndex: 10,
        flex: 0,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 40,
        paddingTop: 20,
    },
    profileCard: {
        backgroundColor: colors.surface,
        padding: 24,
        borderRadius: 20,
        marginBottom: 20,
        borderWidth: 1.5,
        borderColor: colors.border,
        ...ThemeFx.shadowSm,
    },
    profileInfo: {
        marginBottom: 24,
    },
    profileName: {
        fontSize: 24,
        fontWeight: '900',
        color: colors.text,
        letterSpacing: -0.5,
    },
    profileUsername: {
        fontSize: 15,
        color: colors.textMuted,
        fontWeight: '700',
        marginTop: 2,
    },
    profileStats: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '700',
        marginBottom: 16,
    },
    profileMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        marginBottom: 16,
    },
    profileVisibilityBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surfaceLighter,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        gap: 8,
        borderWidth: 1,
        borderColor: colors.border,
    },
    profileVisibilityText: {
        fontSize: 12,
        fontWeight: '800',
        color: colors.textMuted,
    },
    profileEditBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primary.DEFAULT,
        paddingVertical: 10,
        borderRadius: 12,
        gap: 8,
        ...ThemeFx.shadowSm,
    },
    profileEditBtnText: {
        color: colors.onPrimary,
        fontSize: 13,
        fontWeight: '900',
        letterSpacing: 0.5,
    },
    idBox: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: withAlpha(colors.textMuted, '05'),
        padding: 14,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: colors.border,
        borderStyle: 'dashed',
    },
    idText: {
        fontSize: 12,
        color: colors.textMuted,
        fontWeight: '600',
        fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    },
    tabsMenuWrapper: {
        marginBottom: 20,
    },
    tabsMenu: {
        flexDirection: 'row',
        backgroundColor: colors.surface,
        borderRadius: 16,
        padding: 6,
        borderWidth: 1.5,
        borderColor: colors.border,
        ...ThemeFx.shadowSm,
    },
    tabBtn: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        borderRadius: 12,
    },
    tabBtnActive: {
        backgroundColor: colors.primary.DEFAULT,
        ...ThemeFx.shadowSm,
    },
    tabText: {
        fontSize: 13,
        fontWeight: '800',
        color: colors.textMuted,
    },
    tabTextActive: {
        color: colors.onPrimary,
    },
    tabContent: {
        flex: 1,
    },
    rankingHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    rankingSegmentRow: {
        flexDirection: 'row',
        backgroundColor: colors.surface,
        padding: 4,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
    },
    segmentBtn: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
    },
    segmentBtnActive: {
        backgroundColor: withAlpha(colors.primary.DEFAULT, '15'),
    },
    segmentText: {
        fontSize: 12,
        fontWeight: '800',
        color: colors.textMuted,
    },
    segmentTextActive: {
        color: colors.primary.DEFAULT,
    },
    infoBtn: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    friendRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: colors.surface,
        padding: 18,
        borderRadius: 20,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: colors.border,
        ...ThemeFx.shadowSm,
    },
    highlightRow: {
        borderColor: colors.primary.DEFAULT,
        backgroundColor: colors.surfaceLighter,
        borderWidth: 2,
    },
    rankRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    rankNumber: {
        fontSize: 22,
        fontWeight: '900',
        fontStyle: 'italic',
        width: 32,
        textAlign: 'center',
    },
    friendName: {
        fontSize: 16,
        fontWeight: '900',
        color: colors.text,
        letterSpacing: -0.3,
    },
    friendStatus: {
        fontSize: 13,
        color: colors.textMuted,
        fontWeight: '600',
    },
    streakBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: withAlpha(colors.red, '10'),
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
    },
    streakText: {
        fontSize: 11,
        fontWeight: '900',
        color: colors.red,
        textTransform: 'uppercase',
    },
    // Comparison Styles
    expandedComparisonBox: {
        marginHorizontal: 8,
        marginTop: -8,
        marginBottom: 16,
        backgroundColor: withAlpha(colors.surfaceLighter, '80'),
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: colors.border,
        borderTopWidth: 0,
    },
    compareHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 20,
    },
    compareTitle: {
        fontSize: 14,
        fontWeight: '900',
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    compareRow: {
        marginBottom: 20,
    },
    compareRowHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    compareExerciseName: {
        fontSize: 14,
        fontWeight: '800',
        color: colors.text,
    },
    compareDiff: {
        fontSize: 12,
        fontWeight: '900',
    },
    compareBars: {
        flexDirection: 'row',
        gap: 12,
    },
    compareBarContainer: {
        flex: 1,
    },
    compareValueRow: {
        backgroundColor: colors.surface,
        height: 48,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    compareValueHighlightBox: {
        backgroundColor: withAlpha(colors.green, '10'),
        borderColor: withAlpha(colors.green, '40'),
    },
    compareValue: {
        fontSize: 16,
        fontWeight: '900',
        color: colors.text,
    },
    compareValueHighlight: {
        color: colors.green,
    },
    compareLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: colors.textMuted,
        textAlign: 'center',
        marginTop: 6,
        textTransform: 'uppercase',
    },
    compareEmptyText: {
        fontSize: 13,
        color: colors.textMuted,
        textAlign: 'center',
        fontStyle: 'italic',
        marginVertical: 10,
    },
    // Inbox components
    premiumCard: {
        backgroundColor: colors.surface,
        borderRadius: 24,
        padding: 24,
        borderWidth: 1.5,
        borderColor: colors.border,
        ...ThemeFx.shadowLg,
    },
    premiumHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        gap: 16,
    },
    premiumIconBox: {
        width: 56,
        height: 56,
        borderRadius: 18,
        backgroundColor: colors.primary.DEFAULT,
        alignItems: 'center',
        justifyContent: 'center',
        ...ThemeFx.shadowSm,
    },
    premiumTitle: {
        fontSize: 18,
        fontWeight: '900',
        color: colors.text,
        letterSpacing: -0.5,
    },
    premiumSender: {
        fontSize: 14,
        color: colors.primary.DEFAULT,
        fontWeight: '700',
    },
    premiumBody: {
        backgroundColor: colors.surfaceLighter,
        padding: 16,
        borderRadius: 16,
        marginBottom: 20,
    },
    premiumDescription: {
        fontSize: 14,
        color: colors.text,
        lineHeight: 20,
        fontWeight: '500',
    },
    premiumActions: {
        flexDirection: 'row',
        gap: 12,
    },
    premiumBtnPrimary: {
        flex: 1,
        backgroundColor: colors.primary.DEFAULT,
        paddingVertical: 14,
        borderRadius: 14,
        alignItems: 'center',
        ...ThemeFx.shadowSm,
    },
    premiumBtnTextPrimary: {
        color: colors.onPrimary,
        fontSize: 14,
        fontWeight: '900',
    },
    premiumBtnSecondary: {
        paddingHorizontal: 20,
        paddingVertical: 14,
        borderRadius: 14,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
    },
    premiumBtnTextSecondary: {
        color: colors.textMuted,
        fontSize: 14,
        fontWeight: '800',
    },
    premiumResolved: {
        alignItems: 'center',
        paddingVertical: 10,
    },
    premiumStatusText: {
        fontSize: 14,
        fontWeight: '900',
        textTransform: 'uppercase',
    },
    activityRow: {
        backgroundColor: colors.surface,
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: colors.border,
        ...ThemeFx.shadowSm,
    },
    activityHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        marginBottom: 16,
    },
    activityIconBox: {
        width: 44,
        height: 44,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    activityUser: {
        fontSize: 15,
        fontWeight: '900',
        color: colors.text,
    },
    activityDesc: {
        fontSize: 13,
        color: colors.text,
        fontWeight: '600',
    },
    activityDate: {
        fontSize: 11,
        color: colors.textMuted,
        fontWeight: '500',
    },
    activityFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: withAlpha(colors.border, '50'),
    },
    kudoBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: colors.surfaceLighter,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
    },
    kudoBtnActive: {
        backgroundColor: withAlpha(colors.yellow, '15'),
        borderColor: withAlpha(colors.yellow, '30'),
    },
    kudoBtnDisabled: {
        opacity: 0.8,
    },
    kudoText: {
        fontSize: 13,
        fontWeight: '900',
        color: colors.textMuted,
    },
    kudoTextActive: {
        color: colors.yellow,
    },
    ownActivityHint: {
        fontSize: 11,
        color: colors.textMuted,
        fontWeight: '700',
        fontStyle: 'italic',
    },
    searchBox: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 20,
    },
    searchInput: {
        flex: 1,
        backgroundColor: colors.surface,
        height: 52,
        borderRadius: 14,
        paddingHorizontal: 16,
        color: colors.text,
        fontSize: 15,
        borderWidth: 1.5,
        borderColor: colors.border,
        fontWeight: '600',
    },
    searchBtn: {
        backgroundColor: colors.primary.DEFAULT,
        paddingHorizontal: 20,
        height: 52,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        ...ThemeFx.shadowSm,
    },
    searchBtnText: {
        color: colors.onPrimary,
        fontSize: 15,
        fontWeight: '900',
    },
    actionsBox: {
        flexDirection: 'row',
        gap: 8,
    },
    btnSmallAccept: {
        backgroundColor: colors.primary.DEFAULT,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
    },
    btnSmallReject: {
        backgroundColor: colors.surfaceLighter,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
    },
    btnSmallText: {
        color: colors.onPrimary,
        fontSize: 12,
        fontWeight: '800',
    },
    emptyText: {
        fontSize: 15,
        color: colors.textMuted,
        textAlign: 'center',
        marginTop: 40,
        fontWeight: '600',
    },
    // Filters
    inboxSecondaryHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 4,
        marginBottom: 16,
        marginTop: 8,
    },
    inboxStatusTitle: {
        fontSize: 16,
        fontWeight: '900',
        color: colors.text,
        letterSpacing: -0.3,
    },
    archiveToggle: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 10,
        backgroundColor: colors.surfaceLighter,
    },
    archiveToggleActive: {
        backgroundColor: colors.primary.DEFAULT,
    },
    archiveToggleText: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.textMuted,
    },
    archiveToggleTextActive: {
        color: colors.onPrimary,
    },
    filterChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: colors.surface,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        ...ThemeFx.shadowSm,
    },
    filterChipActive: {
        backgroundColor: colors.primary.DEFAULT,
        borderColor: colors.primary.DEFAULT,
    },
    filterChipText: {
        fontSize: 12,
        fontWeight: '800',
        color: colors.textMuted,
    },
    filterChipTextActive: {
        color: colors.onPrimary,
    },
    filterSeparator: {
        width: 1,
        height: 20,
        backgroundColor: colors.border,
        marginHorizontal: 4,
        alignSelf: 'center',
    },
    // Modals
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalCard: {
        width: '100%',
        maxWidth: 500,
        backgroundColor: colors.background,
        borderRadius: 24,
        overflow: 'hidden',
        borderWidth: 1.5,
        borderColor: colors.border,
        ...ThemeFx.shadowLg,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 24,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        backgroundColor: colors.surface,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '900',
        color: colors.text,
        letterSpacing: -0.5,
    },
    modalCloseBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: colors.surfaceLighter,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBody: {
        padding: 24,
    },
    modalLabel: {
        fontSize: 14,
        fontWeight: '900',
        color: colors.text,
        marginBottom: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    modalInput: {
        backgroundColor: colors.surface,
        height: 56,
        borderRadius: 14,
        paddingHorizontal: 16,
        color: colors.text,
        fontSize: 16,
        borderWidth: 1.5,
        borderColor: colors.border,
        marginBottom: 8,
        fontWeight: '600',
    },
    modalFieldHint: {
        fontSize: 12,
        color: colors.textMuted,
        marginBottom: 20,
        lineHeight: 18,
        fontWeight: '500',
    },
    privacyRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surfaceLighter,
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: colors.border,
    },
    privacyHint: {
        fontSize: 12,
        color: colors.textMuted,
        marginTop: 2,
        paddingRight: 10,
        fontWeight: '500',
    },
    modalActions: {
        flexDirection: 'row',
        padding: 24,
        gap: 12,
        borderTopWidth: 1.5,
        borderTopColor: colors.border,
        backgroundColor: colors.surface,
    },
    modalCancelBtn: {
        flex: 1,
        height: 56,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    modalCancelText: {
        color: colors.textMuted,
        fontSize: 15,
        fontWeight: '800',
    },
    modalPrimaryBtn: {
        flex: 2,
        height: 56,
        backgroundColor: colors.primary.DEFAULT,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        ...ThemeFx.shadowSm,
    },
    modalPrimaryText: {
        color: colors.onPrimary,
        fontSize: 15,
        fontWeight: '900',
        textTransform: 'uppercase',
    },
    // Friend Modal specifically
    friendModalUsername: {
        fontSize: 16,
        color: colors.primary.DEFAULT,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 4,
    },
    friendModalStatus: {
        fontSize: 14,
        color: colors.textMuted,
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 24,
    },
    friendInfoCard: {
        backgroundColor: colors.surfaceLighter,
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: colors.border,
    },
    friendInfoLabel: {
        fontSize: 12,
        fontWeight: '900',
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 8,
    },
    friendInfoId: {
        fontSize: 13,
        color: colors.text,
        fontWeight: '700',
        flex: 1,
    },
    friendInfoCopyBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        padding: 12,
        borderRadius: 12,
        gap: 8,
        borderWidth: 1,
        borderColor: colors.border,
        marginBottom: 16,
    },
    modalActionsStack: {
        padding: 24,
        gap: 12,
        borderTopWidth: 1.5,
        borderTopColor: colors.border,
        backgroundColor: colors.surface,
    },
    // Score Info Modal
    infoCard: {
        backgroundColor: colors.surface,
        borderRadius: 20,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.border,
    },
    infoMainValue: {
        fontSize: 32,
        fontWeight: '900',
        color: colors.primary.DEFAULT,
        textAlign: 'center',
        marginVertical: 12,
        letterSpacing: -1,
    },
    infoGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginTop: 8,
    },
    infoItem: {
        width: '48%',
        backgroundColor: colors.surfaceLighter,
        borderRadius: 14,
        padding: 12,
        borderWidth: 1,
        borderColor: colors.border,
    },
    infoItemLabel: {
        fontSize: 10,
        fontWeight: '800',
        color: colors.textMuted,
        textTransform: 'uppercase',
        marginBottom: 4,
    },
    infoItemValue: {
        fontSize: 14,
        fontWeight: '900',
        color: colors.text,
    },
    infoStreakRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: withAlpha(colors.border, '50'),
    },
    infoStreakLabel: {
        fontSize: 13,
        fontWeight: '700',
        color: colors.text,
    },
    infoStreakValue: {
        fontSize: 14,
        fontWeight: '900',
        color: colors.primary.DEFAULT,
    },
    infoStreakBestia: {
        backgroundColor: colors.red,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        marginTop: 8,
        ...ThemeFx.shadowSm,
    },
    infoIconBox: {
        width: 48,
        height: 48,
        borderRadius: 14,
        backgroundColor: withAlpha(colors.yellow, '15'),
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: withAlpha(colors.yellow, '20'),
    },
    formulaBox: {
        backgroundColor: colors.surface,
        borderRadius: 20,
        padding: 24,
        alignItems: 'center',
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: colors.border,
        marginVertical: 12,
    },
    formulaTitle: {
        fontSize: 12,
        fontWeight: '900',
        color: colors.textMuted,
        textTransform: 'uppercase',
        marginBottom: 10,
        letterSpacing: 1,
    },
    formulaText: {
        fontSize: 16,
        fontWeight: '900',
        color: colors.text,
        textAlign: 'center',
        lineHeight: 24,
    },
    eventBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.yellow,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        gap: 8,
    },
    eventBadgeText: {
        color: colors.black,
        fontSize: 12,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    weatherBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.primary.DEFAULT,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        gap: 8,
    },
    weatherBadgeText: {
        color: colors.onPrimary,
        fontSize: 12,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    locationBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surfaceLighter,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        gap: 8,
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    locationBadgeText: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    activeEventBadge: {
        backgroundColor: colors.yellow,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 8,
    },
    activeEventBadgeText: {
        color: colors.onPrimary,
        fontSize: 10,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    detailModalCard: {
        width: '90%',
        maxWidth: 400,
        backgroundColor: colors.surface,
        borderRadius: 20,
        padding: 28,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        ...ThemeFx.shadowLg,
    },
    detailIconCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
        borderWidth: 1.5,
        borderColor: colors.primary.DEFAULT,
        backgroundColor: colors.isDark ? withAlpha(colors.primary.DEFAULT, '15') : colors.surfaceLighter,
    },
    detailTitle: {
        fontSize: 24,
        fontWeight: '900',
        color: colors.text,
        textAlign: 'center',
        marginBottom: 8,
        letterSpacing: -0.5,
    },
    detailDesc: {
        fontSize: 15,
        color: colors.textMuted,
        textAlign: 'center',
        lineHeight: 22,
        fontWeight: '500',
        marginBottom: 28,
    },
    detailInfoGrid: {
        width: '100%',
        backgroundColor: colors.surfaceLighter,
        borderRadius: 20,
        padding: 24,
        gap: 16,
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    detailInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    detailInfoLabel: {
        fontSize: 12,
        color: colors.textMuted,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    detailInfoValue: {
        fontSize: 16,
        color: colors.text,
        fontWeight: '900',
    },
    detailCloseBtn: {
        marginTop: 28,
        width: '100%',
        paddingVertical: 18,
        borderRadius: 16,
        backgroundColor: colors.primary.DEFAULT,
        alignItems: 'center',
        ...ThemeFx.shadowSm,
    },
    detailCloseText: {
        color: colors.onPrimary,
        fontSize: 15,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    // Goal System
    goalsTrigger: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: colors.surfaceLighter,
        padding: 18,
        borderRadius: 20,
        marginTop: 18,
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    goalsTriggerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    goalsTriggerTitle: {
        fontSize: 15,
        fontWeight: '900',
        color: colors.text,
        letterSpacing: -0.3,
    },
    goalsTriggerRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    goalsSummaryText: {
        fontSize: 13,
        fontWeight: '800',
        color: colors.primary.DEFAULT,
        textTransform: 'uppercase',
    },
    goalsExpanded: {
        marginTop: 12,
        backgroundColor: colors.surfaceLighter,
        borderRadius: 16,
        padding: 16,
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    goalsDesc: {
        fontSize: 13,
        color: colors.textMuted,
        lineHeight: 18,
        marginBottom: 16,
        fontWeight: '500',
    },
    daysRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 6,
    },
    dayChip: {
        flex: 1,
        height: 44,
        borderRadius: 12,
        backgroundColor: colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    dayChipActive: {
        backgroundColor: colors.primary.DEFAULT,
        borderColor: colors.primary.DEFAULT,
    },
    dayChipText: {
        fontSize: 14,
        fontWeight: '900',
        color: colors.textMuted,
    },
    dayChipTextActive: {
        color: colors.onPrimary,
    },
    // Action Rows & Buttons
    dualActionRow: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 8,
    },
    modalDangerBtn: {
        flex: 1,
        backgroundColor: withAlpha(colors.red, '10'),
        borderWidth: 1.5,
        borderColor: withAlpha(colors.red, '30'),
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
    },
    modalDangerText: {
        color: colors.red,
        fontSize: 14,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    modalSecondaryBtn: {
        flex: 1,
        backgroundColor: colors.surfaceLighter,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
    },
    modalSecondaryText: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    friendInfoActionBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        backgroundColor: colors.primary.DEFAULT,
        paddingVertical: 16,
        borderRadius: 16,
        marginTop: 4,
        ...ThemeFx.shadowSm,
    },
    friendInfoActionText: {
        color: colors.onPrimary,
        fontSize: 15,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    // Info Sections
    infoSectionTitle: {
        fontSize: 13,
        fontWeight: '900',
        color: colors.primary.DEFAULT,
        textTransform: 'uppercase',
        letterSpacing: 1.2,
        marginBottom: 8,
        marginTop: 12,
    },
    infoSectionDesc: {
        fontSize: 14,
        color: colors.textMuted,
        lineHeight: 20,
        fontWeight: '500',
        marginBottom: 16,
    },
    infoPointRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: withAlpha(colors.border, '50'),
    },
    infoPointText: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '700',
    },
    infoPointValue: {
        fontSize: 14,
        color: colors.primary.DEFAULT,
        fontWeight: '900',
    },
    inboxSecondaryHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
        paddingHorizontal: 4,
    },
    inboxStatusTitle: {
        fontSize: 14,
        fontWeight: '800',
        color: colors.text,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    archiveToggle: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: colors.surfaceLighter,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
    },
    archiveToggleActive: {
        backgroundColor: colors.primary.DEFAULT,
        borderColor: colors.primary.DEFAULT,
    },
    archiveToggleText: {
        fontSize: 12,
        fontWeight: '800',
        color: colors.textMuted,
    },
    archiveToggleTextActive: {
        color: colors.onPrimary,
    },
    markSeenBtn: {
        padding: 8,
        backgroundColor: withAlpha(colors.textMuted, '10'),
        borderRadius: 10,
    },
    // Collapsible Profile Styles
    mainScroll: {
        flex: 1,
    },
    mainScrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 100,
        paddingTop: 20,
        flexGrow: 1,
    },
    profileHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    profileHeaderExpanded: {
        marginBottom: 16,
    },
    profileInfoWrapper: {
        flex: 1,
        marginRight: 12,
    },
    profileBadgesRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    metaSummaryRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
        gap: 8,
        backgroundColor: colors.surfaceLighter,
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
    },
    metaSummaryText: {
        fontSize: 13,
        color: colors.textMuted,
        fontWeight: '800',
    },
    toggleCollapseWrapper: {
        marginTop: 12,
        alignSelf: 'center',
        width: 64,
        height: 28,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.surfaceLighter,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: withAlpha(colors.border, '50'),
    },
    expandedDetails: {
        marginTop: 8,
    },
    badgeSmall: {
        paddingHorizontal: 8,
    },
});

export const useSocialStyles = () => {
    const { activeTheme } = useTheme();
    const { colors } = activeTheme;
    return useMemo(() => createSocialStyles(colors), [colors]);
};
